# Generated by Django 3.2.5 on 2022-04-01 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('1', 'Stress'), ('2', 'Depression'), ('3', 'Anxiety'), ('4', 'OCD'), ('5', 'Eating Disorders'), ('6', 'Relationships'), ('7', 'Work Stress'), ('8', 'Self Doubt'), ('9', 'Addiction and Substance Abuse'), ('10', 'Suicidal Tendency')], max_length=20)),
                ('title', models.CharField(max_length=30, unique=True)),
                ('subtitle', models.CharField(max_length=75, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.TextField(unique=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='profile_photo')),
                ('favourited_by', models.ManyToManyField(related_name='favourited_blogs', to=settings.AUTH_USER_MODEL)),
                ('therapist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
