# Generated by Django 3.2.5 on 2022-04-01 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_blogs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
