# Generated by Django 3.2.5 on 2022-04-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_guestcontactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='defaultpp.jpg', null=True, upload_to='profile_photo'),
        ),
    ]
